<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central Standard Time (Mexico)">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LTGDL68341"><DocLocation><![CDATA[C:\Users\396713\Documents\Git\Google\Google Search]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Google Search]]></DName>
<Res><![CDATA[Res12]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Casos]]></AName>
<AIter rID="T5" iterID="1" isCountable="False" >
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:02]]></Time>
<TimeTick>1548269042</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:02]]></Time>
<TimeTick>1548269042</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:05]]></Time>
<TimeTick>1548269045</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:05]]></Time>
<TimeTick>1548269045</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Buscar.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["how old is Paul Stanley"]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:05]]></Time>
<TimeTick>1548269045</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Buscar.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Buscar con Google.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:06]]></Time>
<TimeTick>1548269046</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="20" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Buscar con Google.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ resultStats ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:10]]></Time>
<TimeTick>1548269050</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="22" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[[ resultStats ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Search on google]]></Obj>
<Details ><![CDATA[the search was correctly made]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:10]]></Time>
<TimeTick>1548269050</TimeTick>
<NodeArgs eType="User" icon="11" nRep="23" status="Passed" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Search on google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Google ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:12]]></Time>
<TimeTick>1548269052</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="26" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[[ Google ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Stop action iteration replay]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:12]]></Time>
<TimeTick>1548269052</TimeTick>
<NodeArgs eType="General" icon="13" nRep="27" status="Information" >
<Disp><![CDATA[Stop action iteration replay]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="8" status="Passed" >
<Disp><![CDATA[Casos Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T16" iterID="2" isCountable="False" >
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:15]]></Time>
<TimeTick>1548269055</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:15]]></Time>
<TimeTick>1548269055</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Buscar.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Krakow"]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:15]]></Time>
<TimeTick>1548269055</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Buscar.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Buscar con Google.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:16]]></Time>
<TimeTick>1548269056</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Buscar con Google.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ resultStats ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:20]]></Time>
<TimeTick>1548269060</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="39" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[[ resultStats ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="33" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="32" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Search on google]]></Obj>
<Details ><![CDATA[the search was correctly made]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:20]]></Time>
<TimeTick>1548269060</TimeTick>
<NodeArgs eType="User" icon="11" nRep="40" status="Passed" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Search on google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Google ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:22]]></Time>
<TimeTick>1548269062</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="43" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[[ Google ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Stop action iteration replay]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:22]]></Time>
<TimeTick>1548269062</TimeTick>
<NodeArgs eType="General" icon="13" nRep="44" status="Information" >
<Disp><![CDATA[Stop action iteration replay]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="29" status="Passed" >
<Disp><![CDATA[Casos Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T25" iterID="3" isCountable="False" >
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:25]]></Time>
<TimeTick>1548269065</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:25]]></Time>
<TimeTick>1548269065</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Buscar.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Whatever"]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:25]]></Time>
<TimeTick>1548269065</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="51" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Buscar.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Buscar con Google.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:26]]></Time>
<TimeTick>1548269066</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="54" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Buscar con Google.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ resultStats ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:29]]></Time>
<TimeTick>1548269069</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="56" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[[ resultStats ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="50" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="49" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[Search on google]]></Obj>
<Details ><![CDATA[the search was correctly made]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:29]]></Time>
<TimeTick>1548269069</TimeTick>
<NodeArgs eType="User" icon="11" nRep="57" status="Passed" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Search on google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Google ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:32]]></Time>
<TimeTick>1548269072</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="60" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[[ Google ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Stop action iteration replay]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:32]]></Time>
<TimeTick>1548269072</TimeTick>
<NodeArgs eType="General" icon="13" nRep="61" status="Information" >
<Disp><![CDATA[Stop action iteration replay]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="46" status="Passed" >
<Disp><![CDATA[Casos Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T34" iterID="4" isCountable="False" >
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:34]]></Time>
<TimeTick>1548269074</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:34]]></Time>
<TimeTick>1548269074</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Buscar.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Sanguche de milanesa"]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:34]]></Time>
<TimeTick>1548269074</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="68" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Buscar.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Buscar con Google.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:35]]></Time>
<TimeTick>1548269075</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="71" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Buscar con Google.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ resultStats ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:39]]></Time>
<TimeTick>1548269079</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="73" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[[ resultStats ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="67" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="66" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[Search on google]]></Obj>
<Details ><![CDATA[the search was correctly made]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:39]]></Time>
<TimeTick>1548269079</TimeTick>
<NodeArgs eType="User" icon="11" nRep="74" status="Passed" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Search on google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Google ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:41]]></Time>
<TimeTick>1548269081</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="77" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[[ Google ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Stop action iteration replay]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:41]]></Time>
<TimeTick>1548269081</TimeTick>
<NodeArgs eType="General" icon="13" nRep="78" status="Information" >
<Disp><![CDATA[Stop action iteration replay]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="63" status="Passed" >
<Disp><![CDATA[Casos Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T43" iterID="5" isCountable="False" >
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:44]]></Time>
<TimeTick>1548269084</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:44]]></Time>
<TimeTick>1548269084</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Buscar.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Empanadas"]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:44]]></Time>
<TimeTick>1548269084</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="85" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Buscar.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Buscar con Google.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:45]]></Time>
<TimeTick>1548269085</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="88" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Buscar con Google.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ resultStats ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:48]]></Time>
<TimeTick>1548269088</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="90" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[[ resultStats ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="84" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="83" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Search on google]]></Obj>
<Details ><![CDATA[the search was correctly made]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:48]]></Time>
<TimeTick>1548269088</TimeTick>
<NodeArgs eType="User" icon="11" nRep="91" status="Passed" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[Search on google]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Google ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:51]]></Time>
<TimeTick>1548269091</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="94" Source="Casos" SourceLine="-1" >
<Disp><![CDATA[[ Google ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Stop action iteration replay]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[1/23/2019 - 12:44:51]]></Time>
<TimeTick>1548269091</TimeTick>
<NodeArgs eType="General" icon="13" nRep="95" status="Information" >
<Disp><![CDATA[Stop action iteration replay]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="80" status="Passed" >
<Disp><![CDATA[Casos Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</AIter>
<Summary sTime="1/23/2019 - 12:43:57" eTime="1/23/2019 - 12:44:51" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Casos Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Google Search Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="1/23/2019 - 12:43:55" eTime="1/23/2019 - 12:44:51" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Google Search Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>